"""§3a's scoring tests.

Three layers, because they fail differently:

* **Closed forms.** CRPS against the analytic Gaussian value, Kupiec against a
  likelihood ratio computed by hand. If these drift, a metric is wrong and every
  number built on it is wrong with it.
* **Boundaries.** The overlap guard, the missing-baseline argument, the shape of
  :class:`RealisedPath`. These are the invariants that would otherwise be a docstring,
  and each is tested by building the thing that should be rejected.
* **The harness end to end.** No lookahead, a driftless null, and — on a series
  generated by a process with real volatility clustering — a positive CRPS skill.
  That last one is not a view about markets: it is the mechanical claim that a
  correctly specified conditional model beats an unconditional one on data that
  actually conditions.
"""

from __future__ import annotations

import dataclasses
import json
import math

import numpy as np
import pandas as pd
import pytest
from scipy import stats

from aurex.assets.synthetic import SYNTHETIC
from aurex.assets.transforms import LogReturn
from aurex.backtest import backtest_asset, describe_backtest
from aurex.score import (
    MIN_POSITIVE_EVENTS,
    ClearsHurdle,
    HorizonDisplacement,
    HorizonLosses,
    ModelForecaster,
    RandomWalkForecaster,
    RealisedPath,
    Sampling,
    TerminalAbove,
    TouchAbove,
    TouchBelow,
    WalkForwardRequest,
    brier_score,
    chi_square_uniformity,
    christoffersen_independence,
    conditional_coverage,
    crps,
    crps_skill,
    default_events,
    diebold_mariano,
    displacement,
    kupiec,
    pit_value,
    reliability_curve,
    skill_decay,
    uniformity,
    walk_forward,
)
from aurex.score.coverage import MIN_EXPECTED_BREACHES
from aurex.score.sampling import OverlappingWindowsError
from aurex.vol import model_for
from tests.conftest import simulate_gjr_path


def price_series(
    *, periods: int = 1_600, seed: int = 11, start: str = "2016-01-01", **kwargs: float
) -> pd.Series:
    """A price path from a known GJR process, so calibration has a right answer."""
    frame = simulate_gjr_path(periods=periods, seed=seed, start=start, **kwargs)
    values = 100.0 * np.exp(np.cumsum(frame["returns"].to_numpy()))
    return pd.Series(values, index=frame.index, name="price")


#: Enough asymmetry and vol-of-vol that conditioning on today's variance is worth
#: something. The default process in ``conftest`` is deliberately milder.
CLUSTERED = {"alpha": 0.10, "gamma": 0.15, "beta": 0.80}


class TestCrps:
    def test_a_single_path_scores_as_absolute_error(self) -> None:
        """One path is a point forecast, and CRPS must collapse to |x - y|."""
        assert crps(np.array([104.0]), 100.0) == pytest.approx(4.0)

    def test_matches_the_analytic_gaussian_value(self) -> None:
        """CRPS(N(0,1), 0) = 2*phi(0) - 1/sqrt(pi), which pins the estimator exactly."""
        sample = stats.norm.rvs(size=200_000, random_state=np.random.default_rng(3))
        expected = 2.0 * stats.norm.pdf(0.0) - 1.0 / math.sqrt(math.pi)

        assert crps(sample, 0.0) == pytest.approx(expected, abs=0.004)

    def test_the_naive_estimator_penalises_a_small_ensemble(self) -> None:
        """The naive form subtracts too little spread, so it scores worse by ~1/M.

        Which is the incentive the fair estimator removes: under the naive score a
        model wins a benchmark by simulating more paths. The gap must also shrink as
        the ensemble grows, or the correction is not the one being described.
        """
        rng = np.random.default_rng(5)
        small = rng.normal(size=100)
        large = rng.normal(size=10_000)

        assert crps(small, 0.3, fair=False) > crps(small, 0.3, fair=True)
        small_gap = crps(small, 0.3, fair=False) - crps(small, 0.3, fair=True)
        large_gap = crps(large, 0.3, fair=False) - crps(large, 0.3, fair=True)

        assert large_gap < small_gap / 50.0

    def test_a_tighter_correct_forecast_scores_better(self) -> None:
        rng = np.random.default_rng(9)
        tight = rng.normal(scale=1.0, size=20_000)
        loose = rng.normal(scale=4.0, size=20_000)

        assert crps(tight, 0.0) < crps(loose, 0.0)

    def test_skill_against_an_identical_score_is_exactly_zero(self) -> None:
        assert crps_skill(2.5, 2.5) == 0.0

    def test_skill_against_a_zero_baseline_is_refused(self) -> None:
        with pytest.raises(ValueError, match="must be positive"):
            crps_skill(1.0, 0.0)


class TestPit:
    """The randomisation is the point; these tests are what it buys."""

    def _values(self, *, ensemble_size: int, observation_scale: float, trials: int) -> np.ndarray:
        rng = np.random.default_rng(17)
        return np.array(
            [
                pit_value(
                    rng.normal(size=ensemble_size),
                    float(rng.normal() * observation_scale),
                    rng=rng,
                )
                for _ in range(trials)
            ]
        )

    def test_a_correct_forecast_gives_uniform_pit_even_for_a_small_ensemble(self) -> None:
        """Fifty paths. The unrandomised PIT would pile mass on the endpoints here."""
        values = self._values(ensemble_size=50, observation_scale=1.0, trials=3_000)
        result = uniformity(values, sampling=Sampling(horizon=1, step=1))

        assert result.p_value > 0.05

    def test_an_overconfident_forecast_is_caught(self) -> None:
        """Observations twice as dispersed as the ensemble: PIT piles at both ends."""
        values = self._values(ensemble_size=200, observation_scale=2.0, trials=3_000)
        result = uniformity(values, sampling=Sampling(horizon=1, step=1))

        assert result.p_value < 1e-6

    def test_pit_stays_inside_the_unit_interval(self) -> None:
        rng = np.random.default_rng(2)
        sample = rng.normal(size=20)

        assert 0.0 < pit_value(sample, 1e9, rng=rng) < 1.0
        assert 0.0 < pit_value(sample, -1e9, rng=rng) < 1.0

    def test_an_empty_ensemble_has_no_pit(self) -> None:
        with pytest.raises(ValueError, match="empty ensemble"):
            pit_value(np.array([]), 1.0, rng=np.random.default_rng(0))


class TestChiSquareComplementsKs:
    """Why both are published: they fail on different shapes."""

    INDEPENDENT = Sampling(horizon=1, step=1)

    def _bin_counts(self, counts: list[int]) -> np.ndarray:
        """Exactly these per-bin counts, spread evenly inside each bin.

        Constructed rather than sampled: the point is a property of the two statistics,
        and sampling noise would only make the comparison flakier without making it
        more real.
        """
        values: list[float] = []
        for index, count in enumerate(counts):
            values.extend((index + (np.arange(count) + 0.5) / count) / len(counts))
        return np.array(sorted(values))

    def test_chi_square_sees_mass_in_one_bin_that_ks_is_weak_against(self) -> None:
        """A displaced bin barely moves the CDF, and the CDF is all KS looks at.

        1,500 observations with 45 moved from the ninth bin into the tenth. The largest
        cumulative deviation is 3%, which KS cannot separate from noise; the two bin
        counts are 30% off their expectation, which chi-square sees immediately. This
        is exactly the shape the gold PIT histograms show, which is why both tests are
        published rather than only the conventional one.
        """
        counts = [150] * 10
        counts[7] -= 45
        counts[8] += 45
        values = self._bin_counts(counts)

        ks = uniformity(values, sampling=self.INDEPENDENT)
        chi = chi_square_uniformity(values, sampling=self.INDEPENDENT)

        assert ks.p_value > 0.10, "KS was expected to miss this"
        assert chi.p_value < 0.01, "chi-square was expected to catch it"

    def test_both_pass_on_a_genuinely_uniform_sample(self) -> None:
        values = np.random.default_rng(5).random(2_000)

        assert uniformity(values, sampling=self.INDEPENDENT).p_value > 0.05
        assert chi_square_uniformity(values, sampling=self.INDEPENDENT).p_value > 0.05

    def test_a_thin_sample_is_flagged_as_an_unreliable_approximation(self) -> None:
        result = chi_square_uniformity(
            np.random.default_rng(3).random(44), sampling=self.INDEPENDENT, bins=10
        )

        assert result.expected_per_bin == pytest.approx(4.4)
        assert result.underpowered
        assert result.describe()["validity_note"] is not None

    def test_it_refuses_overlapping_windows_like_every_other_p_value(self) -> None:
        with pytest.raises(OverlappingWindowsError):
            chi_square_uniformity(np.linspace(0.0, 1.0, 100), sampling=Sampling(horizon=21, step=5))

    def test_degrees_of_freedom_are_one_less_than_the_bins(self) -> None:
        result = chi_square_uniformity(
            np.random.default_rng(1).random(500), sampling=self.INDEPENDENT, bins=8
        )

        assert result.degrees_of_freedom == 7


class TestSampling:
    def test_weekly_forecasts_of_a_monthly_horizon_overlap(self) -> None:
        sampling = Sampling(horizon=21, step=5)

        assert sampling.overlapping
        assert sampling.stride == 5
        assert not sampling.independent().overlapping

    def test_a_horizon_matching_the_step_does_not_overlap(self) -> None:
        assert not Sampling(horizon=5, step=5).overlapping

    def test_thinning_takes_every_stride_th_record(self) -> None:
        thinned = Sampling(horizon=21, step=5).thin(np.arange(20))

        assert list(thinned) == [0, 5, 10, 15]


class TestTestsRefuseOverlappingWindows:
    """The boundary that stops a p-value being computed on dependent observations."""

    OVERLAPPING = Sampling(horizon=21, step=5)

    def test_kupiec_refuses(self) -> None:
        with pytest.raises(OverlappingWindowsError, match="overlap"):
            kupiec(np.zeros(100, dtype=bool), expected_rate=0.05, sampling=self.OVERLAPPING)

    def test_christoffersen_refuses(self) -> None:
        with pytest.raises(OverlappingWindowsError, match="overlap"):
            christoffersen_independence(
                np.zeros(100, dtype=bool), expected_rate=0.05, sampling=self.OVERLAPPING
            )

    def test_the_pit_uniformity_test_refuses(self) -> None:
        with pytest.raises(OverlappingWindowsError, match="overlap"):
            uniformity(np.linspace(0.0, 1.0, 50), sampling=self.OVERLAPPING)

    def test_the_message_says_how_to_thin(self) -> None:
        with pytest.raises(OverlappingWindowsError, match="every 5th record"):
            kupiec(np.zeros(10, dtype=bool), expected_rate=0.05, sampling=self.OVERLAPPING)


class TestKupiec:
    INDEPENDENT = Sampling(horizon=5, step=5)

    def _flags(self, n: int, breaches: int) -> np.ndarray:
        flags = np.zeros(n, dtype=bool)
        flags[np.linspace(0, n - 1, breaches, dtype=int)] = True
        return flags

    def test_a_perfect_rate_scores_exactly_zero(self) -> None:
        result = kupiec(self._flags(1_000, 50), expected_rate=0.05, sampling=self.INDEPENDENT)

        assert result.statistic == pytest.approx(0.0, abs=1e-9)
        assert result.p_value == pytest.approx(1.0)

    def test_a_doubled_rate_matches_the_hand_computed_likelihood_ratio(self) -> None:
        """-2[900 ln.95 + 100 ln.05 - 900 ln.9 - 100 ln.1] = 41.3084."""
        result = kupiec(self._flags(1_000, 100), expected_rate=0.05, sampling=self.INDEPENDENT)

        assert result.statistic == pytest.approx(41.3084, abs=1e-3)
        assert result.p_value is not None and result.p_value < 1e-8

    def test_zero_breaches_is_scored_rather_than_crashing(self) -> None:
        """0 * log(0) is a defined term here, and a model that never breaches is wrong."""
        result = kupiec(np.zeros(100, dtype=bool), expected_rate=0.05, sampling=self.INDEPENDENT)

        assert result.statistic == pytest.approx(10.2587, abs=1e-3)
        assert result.detail["breaches"] == 0

    def test_zero_breaches_is_reported_from_the_exact_binomial(self) -> None:
        """The boundary. The chi-square approximation does not hold at x = 0.

        Kupiec's unrestricted maximum sits on the edge of the parameter space there, so
        its likelihood ratio is not chi-square on one degree of freedom. Concretely:
        0 breaches in 44 windows against a 5% quantile gives a chi-square p of 0.034,
        which reads as a rejection, and an exact p of 0.17, which does not.
        """
        result = kupiec(np.zeros(44, dtype=bool), expected_rate=0.05, sampling=self.INDEPENDENT)

        assert result.method == "exact_binomial"
        assert result.detail["chi2_p_value"] == pytest.approx(0.0336, abs=1e-3)
        assert result.p_value == pytest.approx(0.1721, abs=1e-3)
        # 0.95 ** 44, the one-sided reading the two-sided p-value is built from.
        assert result.detail["exact_lower_tail"] == pytest.approx(0.1047, abs=1e-3)
        assert result.detail["boundary_note"] is not None

    def test_all_breaches_is_also_a_boundary(self) -> None:
        result = kupiec(np.ones(30, dtype=bool), expected_rate=0.05, sampling=self.INDEPENDENT)

        assert result.method == "exact_binomial"

    def test_away_from_the_boundary_the_chi_square_is_used_and_the_two_agree(self) -> None:
        """Both are always computed, so the approximation can be checked where it holds."""
        result = kupiec(self._flags(580, 23), expected_rate=0.05, sampling=self.INDEPENDENT)

        assert result.method == "likelihood_ratio_chi2"
        assert result.p_value == pytest.approx(result.detail["chi2_p_value"], abs=1e-5)
        assert result.detail["exact_binomial_p_value"] == pytest.approx(
            result.detail["chi2_p_value"], abs=0.06
        )

    def test_the_joint_test_flags_a_boundary_component(self) -> None:
        """No exact analogue exists for the joint statistic, so it must not pretend."""
        flags = np.zeros(60, dtype=bool)
        flags[0] = True  # one breach, so independence is defined and the rate is not 0
        joint = conditional_coverage(flags, expected_rate=0.05, sampling=self.INDEPENDENT)

        assert joint.detail["boundary_note"] is None

        clean = conditional_coverage(
            np.zeros(60, dtype=bool), expected_rate=0.05, sampling=self.INDEPENDENT
        )
        assert clean.undefined_reason is not None

    def test_a_thin_sample_carries_a_power_note(self) -> None:
        result = kupiec(np.zeros(46, dtype=bool), expected_rate=0.01, sampling=self.INDEPENDENT)

        assert result.power_note is not None
        assert "absence of evidence" in result.power_note

    def test_a_thick_sample_carries_no_power_note(self) -> None:
        result = kupiec(self._flags(1_000, 50), expected_rate=0.05, sampling=self.INDEPENDENT)

        assert result.power_note is None


class TestChristoffersen:
    INDEPENDENT = Sampling(horizon=5, step=5)

    def test_clustered_breaches_are_caught(self) -> None:
        flags = np.zeros(200, dtype=bool)
        flags[:20] = True
        result = christoffersen_independence(flags, expected_rate=0.1, sampling=self.INDEPENDENT)

        assert result.p_value is not None and result.p_value < 0.01
        assert result.detail["breach_rate_after_breach"] > result.detail["breach_rate_after_calm"]

    def test_perfectly_alternating_breaches_are_also_caught(self) -> None:
        """Independence is two-sided: a breach that never repeats is not independent."""
        flags = np.arange(200) % 2 == 0
        result = christoffersen_independence(flags, expected_rate=0.5, sampling=self.INDEPENDENT)

        assert result.p_value is not None and result.p_value < 0.01

    def test_independent_breaches_are_not_flagged(self) -> None:
        flags = np.random.default_rng(23).random(2_000) < 0.05
        result = christoffersen_independence(flags, expected_rate=0.05, sampling=self.INDEPENDENT)

        assert result.p_value is not None and result.p_value > 0.05

    def test_no_breaches_leaves_the_test_undefined_rather_than_comfortable(self) -> None:
        """The failure this exists to prevent: p = 1.0 read as evidence of calibration."""
        result = christoffersen_independence(
            np.zeros(50, dtype=bool), expected_rate=0.01, sampling=self.INDEPENDENT
        )

        assert result.statistic is None
        assert result.p_value is None
        assert result.undefined_reason is not None
        assert "not identified" in result.undefined_reason

    def test_conditional_coverage_is_undefined_when_a_component_is(self) -> None:
        result = conditional_coverage(
            np.zeros(50, dtype=bool), expected_rate=0.01, sampling=self.INDEPENDENT
        )

        assert result.statistic is None
        assert result.undefined_reason is not None

    def test_conditional_coverage_sums_its_components(self) -> None:
        flags = np.random.default_rng(31).random(500) < 0.08
        rate = kupiec(flags, expected_rate=0.05, sampling=self.INDEPENDENT)
        independence = christoffersen_independence(
            flags, expected_rate=0.05, sampling=self.INDEPENDENT
        )
        joint = conditional_coverage(flags, expected_rate=0.05, sampling=self.INDEPENDENT)

        assert rate.statistic is not None and independence.statistic is not None
        assert joint.statistic == pytest.approx(rate.statistic + independence.statistic)


class TestReliability:
    def test_a_constant_climatological_forecast_is_reliable_and_useless(self) -> None:
        """Reliability zero, resolution zero. Only the pair distinguishes it from skill."""
        outcomes = np.array([1.0, 0.0] * 100)
        curve = reliability_curve(np.full(200, 0.5), outcomes)

        assert curve.brier == pytest.approx(0.25)
        assert curve.reliability == pytest.approx(0.0, abs=1e-12)
        assert curve.resolution == pytest.approx(0.0, abs=1e-12)
        assert curve.uncertainty == pytest.approx(0.25)

    def test_the_decomposition_reconstructs_the_score_when_bins_are_pure(self) -> None:
        probabilities = np.repeat([0.05, 0.45, 0.95], 200)
        rng = np.random.default_rng(41)
        outcomes = (rng.random(600) < probabilities).astype(float)
        curve = reliability_curve(probabilities, outcomes)

        assert curve.binning_error == pytest.approx(0.0, abs=1e-12)

    def test_an_overconfident_forecast_has_a_large_reliability_term(self) -> None:
        """Says 90%, happens half the time: the calibration term is (0.9-0.5)^2."""
        outcomes = np.array([1.0, 0.0] * 100)
        curve = reliability_curve(np.full(200, 0.9), outcomes)

        assert curve.reliability == pytest.approx(0.16)

    def test_brier_rejects_a_probability_outside_the_unit_interval(self) -> None:
        with pytest.raises(ValueError, match=r"\[0, 1\]"):
            brier_score(np.array([1.4]), np.array([1.0]))

    def test_empty_bins_are_kept(self) -> None:
        """``min_positives=0`` because this is the axis rule, not the withholding rule."""
        curve = reliability_curve(np.full(10, 0.05), np.zeros(10), min_positives=0)
        empty = [b for b in curve.bins if b.count == 0]

        assert len(empty) == 9
        assert all(b.observed_rate is None for b in empty)


class TestARareEventGetsAScoreButNotADiagram:
    """The pre-registered rule, written before the hurdle event existed.

    Fifteen positives in 580 windows cannot support a ten-bin diagram. The score, the
    base rate and the count survive at any sample size and are what the reader gets.
    """

    def _rare(self, positives: int, n: int = 580) -> tuple[np.ndarray, np.ndarray]:
        outcomes = np.zeros(n)
        outcomes[:positives] = 1.0
        rng = np.random.default_rng(3)
        return np.clip(rng.normal(positives / n, 0.01, n), 0.0, 1.0), outcomes

    def test_below_the_threshold_the_curve_is_withheld(self) -> None:
        curve = reliability_curve(*self._rare(positives=8))

        assert curve.withheld
        assert curve.bins == ()
        assert "too few to draw" in (curve.withheld_reason or "")

    def test_the_score_and_the_count_survive_the_withholding(self) -> None:
        curve = reliability_curve(*self._rare(positives=8))

        assert curve.positives == 8
        assert curve.base_rate == pytest.approx(8 / 580)
        assert curve.brier > 0.0
        assert curve.describe()["positive_events"] == 8

    def test_the_mean_forecast_survives_the_withholding_too(self) -> None:
        """A scalar is not a diagram, and withholding it with one was a reporting bug.

        `mean_forecast` against `base_rate` is the model's bias on this event, and it
        is the number that says whether a modelled tail is the right shape rather than
        merely non-Gaussian. The argument for withholding a ten-bin curve at eight
        positives — each bin resting on one or two events — says nothing about a single
        mean taken over all 580 forecasts. A rare event is where that comparison
        matters most, so withholding it there was exactly backwards.
        """
        probabilities, outcomes = self._rare(positives=8)
        curve = reliability_curve(probabilities, outcomes)

        assert curve.withheld
        assert curve.bins == ()
        assert curve.mean_forecast == pytest.approx(float(np.mean(probabilities)))
        assert curve.describe()["mean_forecast"] == pytest.approx(
            round(float(np.mean(probabilities)), 4)
        )

    def test_the_mean_forecast_is_taken_over_every_forecast_not_the_drawn_bins(
        self,
    ) -> None:
        """Averaging the bin means would weight a bin holding one forecast equally
        with a bin holding five hundred, and would be undefined when none are drawn."""
        probabilities, outcomes = self._rare(positives=40)
        curve = reliability_curve(probabilities, outcomes)

        assert not curve.withheld
        assert curve.mean_forecast == pytest.approx(float(np.mean(probabilities)))
        assert curve.describe()["forecast_bias"] == pytest.approx(
            round(curve.mean_forecast - curve.base_rate, 4)
        )

    def test_at_the_threshold_the_curve_is_drawn(self) -> None:
        curve = reliability_curve(*self._rare(positives=MIN_POSITIVE_EVENTS))

        assert not curve.withheld
        assert curve.bins

    def test_the_threshold_is_the_one_the_coverage_tests_already_use(self) -> None:
        """Taken from the neighbouring test rather than tuned to this event."""
        assert float(MIN_POSITIVE_EVENTS) == MIN_EXPECTED_BREACHES

    def test_a_low_brier_on_a_rare_event_is_not_a_better_forecast(self) -> None:
        """Why the count is published beside the score: these are not comparable."""
        rare = reliability_curve(*self._rare(positives=15))
        coin = reliability_curve(np.full(580, 0.5), np.array([1.0, 0.0] * 290))

        assert rare.brier < coin.brier
        assert rare.uncertainty < coin.uncertainty
        # Against its own uncertainty term the rare event has learned nothing either.
        assert rare.resolution == pytest.approx(0.0, abs=1e-3)


class TestTheHurdleEvent:
    """The one event friction defines, graded by the machinery that already existed."""

    ENSEMBLE = None

    def _ensemble(self, terminals: np.ndarray) -> object:
        from aurex.dist.paths import PathEnsemble

        return PathEnsemble(prices=terminals.reshape(-1, 1), anchor=100.0, diagnostics={})

    def test_it_is_a_binary_event_like_any_other(self) -> None:
        """The design bet: friction changes the level, not the kind of question."""
        from aurex.score.events import BinaryEvent

        assert isinstance(ClearsHurdle(multiple=1.0937), BinaryEvent)

    def test_the_probability_is_the_share_of_paths_clearing_the_hurdle(self) -> None:
        # Deliberately off the boundary: anchor * multiple is a float product, so a
        # terminal sitting exactly on the level is decided by rounding rather than by
        # anything meaningful. Real ensembles land there with probability zero.
        ensemble = self._ensemble(np.array([100.0, 105.0, 111.0, 115.0]))

        assert ClearsHurdle(multiple=1.10).probability(ensemble) == pytest.approx(0.5)

    def test_it_is_resolved_at_the_horizon_not_on_the_way(self) -> None:
        """A round trip is closed at the end; a path that touched and fell back did not
        clear it for the holder this event grades."""
        event = ClearsHurdle(multiple=1.05)
        touched_and_fell_back = RealisedPath(np.array([100.0, 108.0, 101.0]))

        assert event.monitoring == "terminal"
        assert not event.occurred(100.0, touched_and_fell_back)

    def test_a_hurdle_of_zero_or_less_is_refused(self) -> None:
        with pytest.raises(ValueError, match="must exceed 1"):
            ClearsHurdle(multiple=1.0)

    def test_a_horizon_priced_hurdle_is_scored_only_at_its_own_horizon(self) -> None:
        """Accruing friction: the quarterly hurdle is a cost a weekly holder never paid."""
        event = ClearsHurdle(multiple=1.006, label="x", horizon=63)

        assert event.applies_at(63)
        assert not event.applies_at(5)

    def test_a_hurdle_paid_at_the_door_applies_everywhere(self) -> None:
        event = ClearsHurdle(multiple=1.0937, label="x")

        assert all(event.applies_at(h) for h in (5, 21, 63, 252))

    def test_the_price_events_apply_at_every_horizon(self) -> None:
        for event in default_events():
            assert all(event.applies_at(h) for h in (5, 21, 63))

    def test_the_harness_scores_each_event_only_where_it_applies(self) -> None:
        prices = price_series(periods=1_100)
        weekly = ClearsHurdle(multiple=1.01, label="acc", horizon=5)
        quarterly = ClearsHurdle(multiple=1.05, label="acc", horizon=21)

        result = walk_forward(
            prices,
            subject=ModelForecaster(
                model=model_for("gjr_garch"), transform=LogReturn(), n_paths=600
            ),
            baseline=RandomWalkForecaster(transform=LogReturn(), n_paths=600),
            request=WalkForwardRequest(horizons=(5, 21), step=5, min_observations=750),
            events=(TerminalAbove(), weekly, quarterly),
        )
        by_horizon = {
            h.horizon: {e["id"] for e, _, _ in h.events} for h in result.calibration().horizons
        }

        assert weekly.id in by_horizon[5] and weekly.id not in by_horizon[21]
        assert quarterly.id in by_horizon[21] and quarterly.id not in by_horizon[5]
        assert all(TerminalAbove().id in ids for ids in by_horizon.values())

    def test_the_id_carries_the_hurdle_so_two_routes_never_collide(self) -> None:
        first = ClearsHurdle(multiple=1.0937, label="a")
        second = ClearsHurdle(multiple=1.0510, label="b")

        assert first.id != second.id
        assert "9.37" in first.id


class TestRealisedPathIsCloseOnly:
    """The convention guard: there is no intraday extreme to accidentally score against."""

    def test_the_class_carries_closes_and_nothing_else(self) -> None:
        """Adding a high or low here silently redefines every touch event in the engine.

        Both the forecast and the outcome are monitored at session close, and the
        published touch probabilities are declared as floors because of it. A `lows`
        field would raise every realised touch rate without raising a single simulated
        one, and the model would fail a calibration test for a claim it never made.
        """
        assert set(RealisedPath.__slots__) == {"closes"}

    def test_a_path_with_no_sessions_is_refused(self) -> None:
        with pytest.raises(ValueError, match="no sessions"):
            RealisedPath(np.array([]))

    def test_a_touch_is_resolved_on_closes(self) -> None:
        event = TouchBelow(0.05)
        dipped = RealisedPath(np.array([100.0, 96.0, 94.9, 99.0]))
        held = RealisedPath(np.array([100.0, 96.0, 95.1, 99.0]))

        assert event.occurred(100.0, dipped)
        assert not event.occurred(100.0, held)

    def test_touch_events_declare_their_monitoring(self) -> None:
        assert TouchBelow(0.05).monitoring == "session_close"
        assert TouchAbove(0.05).monitoring == "session_close"
        assert TerminalAbove().monitoring == "terminal"

    def test_monitoring_cannot_be_overridden_by_construction(self) -> None:
        """It is a property, not a field: a caller cannot declare a convention it lacks."""
        with pytest.raises(TypeError):
            TouchBelow(0.05, monitoring="terminal")  # type: ignore[call-arg]

    def test_default_events_need_no_friction(self) -> None:
        ids = {event.id for event in default_events((0.05, 0.10))}

        assert ids == {
            "direction_up",
            "touch_below_5pct",
            "touch_above_5pct",
            "touch_below_10pct",
            "touch_above_10pct",
        }


class TestTheNullIsDriftless:
    def test_a_trending_history_does_not_tilt_the_random_walk(self) -> None:
        """The mean is removed, so the null cannot inherit twenty years of appreciation."""
        prices = price_series(periods=800)
        drift = np.exp(0.002 * np.arange(len(prices)))
        trending = pd.Series(prices.to_numpy() * drift, index=prices.index)

        forecaster = RandomWalkForecaster(transform=LogReturn(), n_paths=500, min_observations=100)
        flat = forecaster.forecast(prices, horizons=(21,), seed=1)[21]
        tilted = forecaster.forecast(trending, horizons=(21,), seed=1)[21]

        assert np.allclose(flat.prices / flat.anchor, tilted.prices / tilted.anchor)

    def test_the_median_path_goes_nowhere(self) -> None:
        prices = price_series(periods=800)
        forecaster = RandomWalkForecaster(
            transform=LogReturn(), n_paths=8_000, min_observations=100
        )
        ensemble = forecaster.forecast(prices, horizons=(21,), seed=2)[21]
        median = float(np.median(ensemble.terminal())) / ensemble.anchor

        assert median == pytest.approx(1.0, abs=0.01)

    def test_the_null_reports_that_it_has_no_conditional_variance(self) -> None:
        forecaster = RandomWalkForecaster(transform=LogReturn())

        assert forecaster.describe()["model"]["drift"].startswith("zero by construction")


class TestDriftDisplacement:
    """The square-root law, tested where the answer is constructed rather than observed."""

    def _points(
        self, drift_ratio: float, horizons: tuple[int, ...]
    ) -> tuple[HorizonDisplacement, ...]:
        """Mean PIT a sample displaced by ``drift_ratio`` per session would produce."""
        return tuple(
            HorizonDisplacement(
                horizon=h,
                mean_pit=float(stats.norm.cdf(drift_ratio * np.sqrt(h) / np.sqrt(2.0))),
                observations=500,
            )
            for h in horizons
        )

    def test_it_recovers_a_drift_it_was_given(self) -> None:
        fitted = displacement(self._points(0.04, (5, 10, 21, 42, 63)))

        assert fitted is not None
        assert fitted.r_squared > 0.99
        assert fitted.implied_standardised_drift == pytest.approx(0.04, rel=0.05)

    def test_a_sample_with_no_displacement_fits_nothing(self) -> None:
        flat = tuple(
            HorizonDisplacement(horizon=h, mean_pit=0.5, observations=500) for h in (5, 21, 63)
        )
        fitted = displacement(flat)

        assert fitted is not None
        assert fitted.slope == pytest.approx(0.0)
        assert fitted.implied_standardised_drift == pytest.approx(0.0)

    def test_a_displacement_that_does_not_scale_as_root_h_fits_badly(self) -> None:
        """The law has to be falsifiable, or a good fit means nothing."""
        linear = tuple(
            HorizonDisplacement(horizon=h, mean_pit=0.5 + 0.001 * h, observations=500)
            for h in (5, 10, 21, 42, 63)
        )
        fitted = displacement(linear)

        assert fitted is not None
        assert fitted.r_squared < displacement(self._points(0.04, (5, 10, 21, 42, 63))).r_squared  # type: ignore[union-attr]

    def test_two_horizons_are_not_enough_to_test_a_one_parameter_law(self) -> None:
        assert displacement(self._points(0.04, (5, 21))) is None


class TestBothSidesShareOneDriftPolicy:
    """The §0 settlement: the model and its null are demeaned or neither is.

    FHS resamples empirical residuals, and in a sample that rose those have a positive
    mean — so the model used to carry a drift while the null had been stripped of one,
    and the gap between them was scored as skill. The residuals still carry it; the
    pool the simulation draws from does not.
    """

    def _rising(self, periods: int = 1_200, rate: float = 0.0008) -> pd.Series:
        prices = price_series(periods=periods)
        return pd.Series(
            prices.to_numpy() * np.exp(rate * np.arange(len(prices))), index=prices.index
        )

    def test_a_rising_history_still_leaves_drift_in_the_fitted_residuals(self) -> None:
        """The thing being corrected for is real, and it is not the fitted mean."""
        fit = model_for("gjr_garch").fit(LogReturn().to_returns(self._rising()))

        assert fit.mu == 0.0
        assert float(fit.standardized_residuals.mean()) > 0.05

    def test_the_model_no_longer_forecasts_that_drift_forward(self) -> None:
        """The median simulated price sits at spot, which is what §0 asks a null-free
        distribution to do. Before the pool was demeaned it sat measurably above."""
        rising = self._rising()
        demeaned = ModelForecaster(
            model=model_for("gjr_garch"), transform=LogReturn(), n_paths=4_000
        )
        carrying = dataclasses.replace(demeaned, demean_residuals=False)
        anchor = float(rising.iloc[-1])

        centred = float(np.median(demeaned.forecast(rising, horizons=(63,), seed=4)[63].terminal()))
        drifted = float(np.median(carrying.forecast(rising, horizons=(63,), seed=4)[63].terminal()))

        assert centred == pytest.approx(anchor, rel=0.01)
        assert drifted > anchor * 1.02

    def test_the_drift_policy_picks_its_own_like_for_like_null(self) -> None:
        """Derived from the flag, so the two cannot be configured to disagree."""
        demeaned = ModelForecaster(model=model_for("gjr_garch"), transform=LogReturn())
        carrying = dataclasses.replace(demeaned, demean_residuals=False)

        assert demeaned.like_for_like_null == "random_walk"
        assert carrying.like_for_like_null == "random_walk_drift_matched"
        assert demeaned.describe()["residual_pool"]["demeaned"] is True

    def test_the_backtest_gives_both_sides_the_same_policy(self) -> None:
        prices = price_series(periods=400)
        result = backtest_asset(
            SYNTHETIC,
            prices=prices,
            request=WalkForwardRequest(horizons=(5,), step=5, min_observations=100),
            n_paths=300,
        )

        assert result.subject["residual_pool"]["demeaned"] is True
        assert result.subject["like_for_like_null"] == result.baseline["label"]
        assert describe_backtest(SYNTHETIC, result)["like_for_like_null"]["null"] == "random_walk"

    def test_a_drift_carrying_run_moves_its_own_like_for_like_null(self) -> None:
        """The declared option stays available, and it takes its fair null with it."""
        prices = price_series(periods=400)
        result = backtest_asset(
            SYNTHETIC,
            prices=prices,
            request=WalkForwardRequest(horizons=(5,), step=5, min_observations=100),
            n_paths=300,
            demean_residuals=False,
        )
        described = describe_backtest(SYNTHETIC, result)

        assert result.subject["residual_pool"]["demeaned"] is False
        assert described["like_for_like_null"]["null"] == "random_walk_drift_matched"
        # The required null is still §0's, so turning the option on cannot remove the
        # comparison the project committed to.
        assert result.baseline["label"] == "random_walk"

    def test_the_two_nulls_differ_only_in_their_drift(self) -> None:
        prices = price_series(periods=800)
        drift = np.exp(0.001 * np.arange(len(prices)))
        rising = pd.Series(prices.to_numpy() * drift, index=prices.index)

        demeaned = RandomWalkForecaster(transform=LogReturn(), n_paths=4_000, min_observations=100)
        matched = dataclasses.replace(demeaned, demean=False)

        flat_median = float(
            np.median(demeaned.forecast(rising, horizons=(63,), seed=4)[63].terminal())
        )
        drifted_median = float(
            np.median(matched.forecast(rising, horizons=(63,), seed=4)[63].terminal())
        )

        assert demeaned.label == "random_walk"
        assert matched.label == "random_walk_drift_matched"
        assert drifted_median > flat_median

    def test_the_label_cannot_be_forged(self) -> None:
        """It is derived from ``demean``, so a drifting null cannot claim to be driftless."""
        with pytest.raises(TypeError):
            RandomWalkForecaster(transform=LogReturn(), label="random_walk")  # type: ignore[call-arg]

    def test_a_second_null_is_reported_beside_the_required_one_not_instead(self) -> None:
        prices = price_series(periods=1_000)
        matched = RandomWalkForecaster(
            transform=LogReturn(), n_paths=800, min_observations=100, demean=False
        )
        result = walk_forward(
            prices,
            subject=ModelForecaster(
                model=model_for("gjr_garch"), transform=LogReturn(), n_paths=800
            ),
            baseline=RandomWalkForecaster(transform=LogReturn(), n_paths=800, min_observations=100),
            request=WalkForwardRequest(horizons=(5, 21), step=5, min_observations=750),
            extra_baselines=(matched,),
        )
        horizon = result.calibration().horizons[0]

        assert horizon.crps_baseline > 0.0
        assert "random_walk_drift_matched" in horizon.crps_alternatives
        described = horizon.describe()["crps"]
        assert described["skill_score"] is not None
        assert "random_walk_drift_matched" in described["alternative_nulls"]


class TestDieboldMariano:
    """The test that decides whether a skill score is a finding or a rounding error."""

    def _differential(self, *, mean: float, n: int, ma: int, seed: int) -> np.ndarray:
        """A loss differential with the MA dependence overlapping windows produce."""
        rng = np.random.default_rng(seed)
        raw = rng.normal(0.0, 1.0, n + ma)
        return np.convolve(raw, np.ones(ma + 1) / (ma + 1.0), mode="valid") + mean

    def test_on_a_disjoint_series_it_is_exactly_the_paired_t_test(self) -> None:
        """The HLN correction at an overlap of one *is* the ``t`` statistic, algebraically.

        Not an approximation to check loosely: ``sqrt((n-1)/n)`` applied to a statistic
        built on the ``1/n`` autocovariance divisor gives back ``dbar / (s / sqrt(n))``.
        If this ever drifts, either the divisor or the correction has been changed and
        every p-value in the calibration report moved with it.
        """
        differential = self._differential(mean=0.3, n=60, ma=0, seed=3)
        result = diebold_mariano(
            differential, np.zeros(differential.size), sampling=Sampling(5, 5), null="rw"
        )
        expected = stats.ttest_1samp(differential, 0.0)

        assert result.hac_lag == 0
        assert result.statistic == pytest.approx(float(expected.statistic))
        assert result.p_value == pytest.approx(float(expected.pvalue))

    def test_the_truncation_lag_is_the_overlap_in_records_not_the_horizon(self) -> None:
        """``h - 1`` is the textbook rule for forecasts made every session, and it is
        recovered at ``step = 1``. Sampled weekly, a 63-session window overlaps the
        previous twelve records, not the previous sixty-two."""
        differential = self._differential(mean=0.0, n=200, ma=12, seed=5)
        null = np.zeros(differential.size)

        weekly = diebold_mariano(differential, null, sampling=Sampling(63, 5), null="rw")
        daily = diebold_mariano(differential, null, sampling=Sampling(63, 1), null="rw")

        assert weekly.hac_lag == 12
        assert daily.hac_lag == 62

    def test_ignoring_the_overlap_manufactures_significance(self) -> None:
        """The whole reason the lag is derived from the sampling rather than defaulted."""
        differential = self._differential(mean=0.06, n=600, ma=12, seed=7)
        null = np.zeros(differential.size)

        honest = diebold_mariano(differential, null, sampling=Sampling(63, 5), null="rw")
        pretending = diebold_mariano(differential, null, sampling=Sampling(5, 5), null="rw")

        assert abs(pretending.statistic) > 2.5 * abs(honest.statistic)
        assert pretending.p_value < honest.p_value

    def test_a_model_that_really_is_better_is_detected(self) -> None:
        """Power, so the test is not just a machine for failing to reject."""
        rng = np.random.default_rng(11)
        baseline = rng.gamma(shape=4.0, scale=1.0, size=400)
        model = baseline * 0.85

        result = diebold_mariano(model, baseline, sampling=Sampling(5, 5), null="rw")

        assert result.favours_model
        assert result.p_value is not None and result.p_value < 0.001

    def test_the_sign_convention_is_the_differentials_not_the_skill_scores(self) -> None:
        """``d = model - null``, so the model winning shows up as a negative statistic."""
        rng = np.random.default_rng(13)
        baseline = rng.gamma(shape=4.0, scale=1.0, size=200)

        better = diebold_mariano(baseline * 0.9, baseline, sampling=Sampling(5, 5), null="rw")
        worse = diebold_mariano(baseline * 1.1, baseline, sampling=Sampling(5, 5), null="rw")

        assert better.statistic is not None and better.statistic < 0.0
        assert worse.statistic is not None and worse.statistic > 0.0
        assert better.favours_model and not worse.favours_model

    def test_the_small_sample_correction_always_shrinks_the_statistic(self) -> None:
        """HLN scales by something below one, so it can only ever make rejection harder."""
        differential = self._differential(mean=0.2, n=50, ma=12, seed=17)
        null = np.zeros(differential.size)
        result = diebold_mariano(differential, null, sampling=Sampling(63, 5), null="rw")

        centred = differential - differential.mean()
        variance = float(np.dot(centred, centred) / centred.size)
        for lag in range(1, result.hac_lag + 1):
            weight = 1.0 - lag / (result.hac_lag + 1.0)
            variance += 2.0 * weight * float(np.dot(centred[lag:], centred[:-lag]) / centred.size)
        uncorrected = differential.mean() / math.sqrt(variance / differential.size)

        assert result.statistic is not None
        assert abs(result.statistic) < abs(uncorrected)

    def test_two_identical_forecasters_leave_nothing_to_test(self) -> None:
        losses = np.array([1.0, 2.0, 3.0, 4.0])
        result = diebold_mariano(losses, losses, sampling=Sampling(5, 5), null="rw")

        assert result.statistic is None and result.p_value is None
        assert result.undefined_reason is not None
        assert "identically" in result.undefined_reason

    def test_a_sample_shorter_than_its_own_overlap_is_refused(self) -> None:
        """Rather than reporting a statistic from autocovariances it cannot estimate."""
        result = diebold_mariano(np.arange(3.0), np.zeros(3), sampling=Sampling(63, 5), null="rw")

        assert result.statistic is None
        assert result.undefined_reason is not None
        assert result.n == 3

    def test_misaligned_series_are_refused(self) -> None:
        with pytest.raises(ValueError, match="align"):
            diebold_mariano(np.zeros(5), np.zeros(4), sampling=Sampling(5, 5), null="rw")

    def test_the_described_block_names_both_corrections(self) -> None:
        result = diebold_mariano(
            np.arange(40.0), np.zeros(40), sampling=Sampling(21, 5), null="random_walk"
        )
        described = result.describe()

        assert described["variance_estimator"] == "newey_west_bartlett"
        assert described["small_sample_correction"] == "harvey_leybourne_newbold"
        assert described["null_compared"] == "random_walk"
        assert described["reference_distribution"] == "t(39)"
        json.dumps(described)


class TestSkillDecay:
    """Skill should fall with the horizon, because conditional variance mean-reverts."""

    def _losses(self, skills: dict[int, float], *, n: int, seed: int) -> tuple[HorizonLosses, ...]:
        """Aligned per-date losses engineered to produce the given skill at each horizon."""
        rng = np.random.default_rng(seed)
        return tuple(
            HorizonLosses(
                horizon=horizon,
                model=(base := rng.gamma(shape=6.0, scale=1.0, size=n)) * (1.0 - skill),
                baseline=base,
            )
            for horizon, skill in sorted(skills.items())
        )

    def test_it_finds_a_decay_it_was_given(self) -> None:
        points = self._losses({5: 0.05, 10: 0.03, 21: 0.015, 42: 0.005, 63: 0.0}, n=300, seed=2)
        fitted = skill_decay(points, block=13, seed=4, draws=800)

        assert fitted is not None
        assert fitted.decays
        assert fitted.p_value < 0.05
        assert fitted.interval[1] < 0.0

    def test_flat_skill_across_horizons_is_not_a_trend(self) -> None:
        points = self._losses({5: 0.02, 10: 0.02, 21: 0.02, 42: 0.02, 63: 0.02}, n=300, seed=6)
        fitted = skill_decay(points, block=13, seed=4, draws=800)

        assert fitted is not None
        assert fitted.p_value > 0.05
        assert fitted.interval[0] < 0.0 < fitted.interval[1]

    def test_a_bootstrap_never_reports_a_p_value_below_its_own_resolution(self) -> None:
        """800 draws cannot resolve 1-in-10,000, and printing 0.0 would claim it could."""
        points = self._losses({5: 0.30, 10: 0.20, 21: 0.10, 42: 0.02, 63: -0.05}, n=300, seed=8)
        fitted = skill_decay(points, block=13, seed=4, draws=800)

        assert fitted is not None
        assert fitted.p_value >= 1.0 / fitted.draws

    def test_two_horizons_are_a_line_rather_than_a_shape(self) -> None:
        assert skill_decay(self._losses({5: 0.05, 63: 0.0}, n=100, seed=9), block=5, seed=1) is None

    def test_horizons_read_at_different_dates_cannot_be_resampled_together(self) -> None:
        rng = np.random.default_rng(10)
        points = (
            HorizonLosses(horizon=5, model=rng.random(50), baseline=rng.random(50) + 1.0),
            HorizonLosses(horizon=21, model=rng.random(50), baseline=rng.random(50) + 1.0),
            HorizonLosses(horizon=63, model=rng.random(40), baseline=rng.random(40) + 1.0),
        )
        with pytest.raises(ValueError, match="same as-of dates"):
            skill_decay(points, block=13, seed=1, draws=100)

    def test_a_horizon_with_mismatched_series_is_refused_at_construction(self) -> None:
        with pytest.raises(ValueError, match="align"):
            HorizonLosses(horizon=5, model=np.zeros(10), baseline=np.zeros(9))


class TestEverySkillScoreCarriesItsTest:
    """§0 asks for a comparison against the null; a comparison without a test is not one."""

    def _report(self) -> object:
        prices = price_series(periods=1_600, **CLUSTERED)
        matched = RandomWalkForecaster(
            transform=LogReturn(), n_paths=1_200, min_observations=100, demean=False
        )
        result = walk_forward(
            prices,
            subject=ModelForecaster(
                model=model_for("gjr_garch"), transform=LogReturn(), n_paths=1_200
            ),
            baseline=RandomWalkForecaster(transform=LogReturn(), n_paths=1_200),
            request=WalkForwardRequest(horizons=(5, 21, 63), step=5, min_observations=750),
            extra_baselines=(matched,),
        )
        return result.calibration()

    def test_one_test_per_null_with_the_required_one_first(self) -> None:
        report = self._report()

        for horizon in report.horizons:  # type: ignore[attr-defined]
            assert len(horizon.skill_tests) == 2
            assert horizon.baseline_test.null == "random_walk"
            assert horizon.skill_tests[1].null == "random_walk_drift_matched"

    def test_the_test_is_run_twice_and_the_counts_differ_where_windows_overlap(self) -> None:
        report = self._report()
        weekly, _, quarterly = report.horizons  # type: ignore[attr-defined]

        assert weekly.baseline_test.overlapping.n == weekly.baseline_test.thinned.n
        assert quarterly.baseline_test.thinned.n < quarterly.baseline_test.overlapping.n
        assert quarterly.baseline_test.thinned.n == quarterly.n_independent

    def test_the_skill_score_and_its_test_agree_on_who_won(self) -> None:
        """Opposite sign conventions, so this catches a differential built backwards."""
        report = self._report()

        for horizon in report.horizons:  # type: ignore[attr-defined]
            for test in horizon.skill_tests:
                if test.skill != 0.0:
                    assert (test.skill > 0.0) == test.overlapping.favours_model

    def test_a_result_needs_both_runs_to_reject_and_to_agree(self) -> None:
        report = self._report()
        horizon = report.horizons[0]  # type: ignore[attr-defined]
        test = horizon.baseline_test

        assert test.significant == (
            test.overlapping.p_value is not None
            and test.thinned.p_value is not None
            and test.overlapping.p_value < 0.05
            and test.thinned.p_value < 0.05
            and test.overlapping.favours_model == test.thinned.favours_model
        )

    def test_the_shape_is_tested_across_horizons(self) -> None:
        report = self._report()

        assert report.skill_decay is not None  # type: ignore[attr-defined]
        assert report.skill_decay.n_dates > 0  # type: ignore[attr-defined]
        assert len(report.skill_decay.points) == 3  # type: ignore[attr-defined]

    def test_the_tests_reach_the_artifact(self) -> None:
        described = self._report().describe()  # type: ignore[attr-defined]
        crps_block = described["horizons"][0]["crps"]

        assert crps_block["significance"]["overlapping_windows_hac"]["p_value"] is not None
        assert crps_block["significance"]["non_overlapping_subsample"]["p_value"] is not None
        alternative = crps_block["alternative_nulls"]["random_walk_drift_matched"]
        assert alternative["significance"]["overlapping_windows_hac"]["test"] == "diebold_mariano"
        assert described["skill_decay"]["p_value"] is not None
        json.dumps(described)


class TestWalkForward:
    REQUEST = WalkForwardRequest(horizons=(5, 21), step=5, min_observations=750)

    def _run(self, prices: pd.Series, request: WalkForwardRequest | None = None) -> object:
        return walk_forward(
            prices,
            subject=ModelForecaster(
                model=model_for("gjr_garch"), transform=LogReturn(), n_paths=1_500
            ),
            baseline=RandomWalkForecaster(transform=LogReturn(), n_paths=1_500),
            request=request or self.REQUEST,
        )

    def test_rewriting_the_future_cannot_change_a_past_forecast(self) -> None:
        """The lookahead test. Nothing after an as-of date may reach the fit or the score."""
        prices = price_series(periods=1_100)
        tamper_from = len(prices) - 200

        tampered = prices.copy()
        tampered.iloc[tamper_from:] *= 3.0

        original = self._run(prices)
        rewritten = self._run(tampered)

        positions = {stamp: i for i, stamp in enumerate(prices.index)}
        after = {(r.as_of, r.horizon): r for r in rewritten.records}  # type: ignore[attr-defined]
        compared = 0
        for record in original.records:  # type: ignore[attr-defined]
            if positions[record.as_of] + record.horizon >= tamper_from:
                continue
            twin = after[(record.as_of, record.horizon)]
            assert twin.pit == record.pit
            assert twin.crps == pytest.approx(record.crps)
            assert twin.realised == pytest.approx(record.realised)
            compared += 1

        assert compared > 50, "the test compared too few untouched records to mean anything"

    def test_every_record_carries_a_baseline_score(self) -> None:
        result = self._run(price_series(periods=1_000))

        assert result.records  # type: ignore[attr-defined]
        assert all(r.crps_baseline > 0.0 for r in result.records)  # type: ignore[attr-defined]

    def test_a_run_without_a_baseline_is_impossible(self) -> None:
        """§0's null hypothesis is a required argument, not a convention."""
        with pytest.raises(TypeError, match="baseline"):
            walk_forward(  # type: ignore[call-arg]
                price_series(periods=900),
                subject=RandomWalkForecaster(transform=LogReturn()),
            )

    def test_records_stop_before_the_horizon_runs_off_the_end(self) -> None:
        prices = price_series(periods=1_000)
        result = self._run(prices)

        for record in result.records:  # type: ignore[attr-defined]
            offset = prices.index.get_loc(record.as_of)
            assert isinstance(offset, int)
            assert offset + record.horizon < len(prices)

    def test_a_history_too_short_to_fit_is_recorded_as_a_skip(self) -> None:
        """A model that cannot be fitted must leave a reason, never a silent gap."""
        prices = price_series(periods=900)
        result = walk_forward(
            prices,
            subject=ModelForecaster(
                model=model_for("gjr_garch", min_observations=880),
                transform=LogReturn(),
                n_paths=200,
            ),
            baseline=RandomWalkForecaster(transform=LogReturn(), n_paths=200),
            request=WalkForwardRequest(horizons=(5,), step=5, min_observations=750),
        )

        assert result.skipped
        assert all("880" in entry.reason for entry in result.skipped)

    def test_unsorted_prices_are_refused(self) -> None:
        prices = price_series(periods=900)
        with pytest.raises(ValueError, match="sorted by date"):
            self._run(prices.iloc[::-1])


class TestTheSampleWindowIsReproducible:
    """A published number has to carry the window it came from.

    Before `--to` existed the run ended at wall-clock, so the sample depended on the
    day the command was typed and no reader could re-derive the published table. These
    tests are about that specific failure: the bound has to hold, it has to bound the
    *outcomes* as well as the forecasts, and it has to be recorded in a form that can
    be passed back.
    """

    REQUEST = WalkForwardRequest(horizons=(5, 21), step=5, min_observations=750)

    def _run(self, prices: pd.Series, request: WalkForwardRequest) -> object:
        return walk_forward(
            prices,
            subject=ModelForecaster(
                model=model_for("gjr_garch"), transform=LogReturn(), n_paths=400
            ),
            baseline=RandomWalkForecaster(transform=LogReturn(), n_paths=400),
            request=request,
        )

    def test_the_end_bound_truncates_the_sample(self) -> None:
        prices = price_series(periods=1_100)
        cut = prices.index[900]

        result = self._run(prices, dataclasses.replace(self.REQUEST, end=cut))

        assert result.sample is not None  # type: ignore[attr-defined]
        assert result.sample.resolved_end == cut  # type: ignore[attr-defined]
        assert result.sample.available_end == prices.index[-1]  # type: ignore[attr-defined]
        assert result.sample.truncated  # type: ignore[attr-defined]
        assert all(record.as_of <= cut for record in result.records)  # type: ignore[attr-defined]

    def test_nothing_after_the_end_bound_is_scored_against(self) -> None:
        """The bound covers realised outcomes, not just as-of dates.

        Filtering only the forecast dates would leave a window near the end scored
        against prices the declared sample says are not in it — which is lookahead
        dressed as a reproducibility flag.
        """
        prices = price_series(periods=1_100)
        cut = prices.index[900]

        truncated = self._run(prices, dataclasses.replace(self.REQUEST, end=cut))
        rewritten = prices.copy()
        rewritten.iloc[901:] *= 5.0
        tampered = self._run(rewritten, dataclasses.replace(self.REQUEST, end=cut))

        before = {(r.as_of, r.horizon): r.crps for r in truncated.records}  # type: ignore[attr-defined]
        after = {(r.as_of, r.horizon): r.crps for r in tampered.records}  # type: ignore[attr-defined]

        assert before.keys() == after.keys()
        assert before == pytest.approx(after)

    def test_the_last_scored_window_ends_inside_the_sample(self) -> None:
        prices = price_series(periods=1_100)
        cut = prices.index[900]

        result = self._run(prices, dataclasses.replace(self.REQUEST, end=cut))

        positions = {stamp: i for i, stamp in enumerate(prices.index)}
        for record in result.records:  # type: ignore[attr-defined]
            assert positions[record.as_of] + record.horizon <= 900

    def test_the_window_is_published_with_both_what_was_asked_and_what_resolved(
        self,
    ) -> None:
        """The default case — no `--to` at all — is the one every published number came
        from, so recording only the request would document the wrong thing."""
        prices = price_series(periods=1_100)

        block = self._run(prices, self.REQUEST).sample.describe()  # type: ignore[attr-defined]

        assert block["requested"]["to"] is None
        assert block["resolved"]["to"] == prices.index[-1].date().isoformat()
        assert block["truncated"] is False
        assert "--to" in block["note"]

    def test_a_sample_ending_before_it_starts_is_refused(self) -> None:
        with pytest.raises(ValueError, match=r"ends .* before it starts"):
            WalkForwardRequest(start=pd.Timestamp("2020-01-01"), end=pd.Timestamp("2019-01-01"))

    def test_an_end_before_the_series_begins_is_refused_with_the_reason(self) -> None:
        prices = price_series(periods=1_100)

        with pytest.raises(ValueError, match="no observations at or before"):
            self._run(prices, dataclasses.replace(self.REQUEST, end=pd.Timestamp("1990-01-01")))


class TestCalibrationReport:
    def _report(self, **process: float) -> object:
        prices = price_series(periods=1_600, **process)
        result = walk_forward(
            prices,
            subject=ModelForecaster(
                model=model_for("gjr_garch"), transform=LogReturn(), n_paths=2_000
            ),
            baseline=RandomWalkForecaster(transform=LogReturn(), n_paths=2_000),
            request=WalkForwardRequest(horizons=(5, 21), step=5, min_observations=750),
        )
        return result.calibration()

    def test_a_correctly_specified_model_produces_uniform_pit(self) -> None:
        """End to end on data from a known GJR process. Deterministic given the seed."""
        report = self._report(**CLUSTERED)
        horizon = report.horizons[0]  # type: ignore[attr-defined]

        assert horizon.pit_uniformity is not None
        assert horizon.pit_uniformity.p_value > 0.05

    def test_conditioning_on_variance_beats_not_conditioning(self) -> None:
        """Mechanical, not a market claim: the data really does condition, so the
        conditional model must score better. If this goes negative the FHS chain has
        stopped propagating the fitted variance."""
        report = self._report(**CLUSTERED)
        horizon = report.horizons[0]  # type: ignore[attr-defined]

        assert horizon.skill > 0.0

    def test_the_independent_count_is_smaller_at_a_longer_horizon(self) -> None:
        report = self._report(**CLUSTERED)
        weekly, monthly = report.horizons  # type: ignore[attr-defined]

        assert weekly.n_independent == weekly.n
        assert monthly.n_independent < monthly.n // 4

    def test_every_p_value_comes_with_its_observation_count(self) -> None:
        report = self._report(**CLUSTERED)

        for horizon in report.horizons:  # type: ignore[attr-defined]
            for level in horizon.coverage:
                assert level.rate_test.n == horizon.n_independent

    def test_the_report_is_json_safe(self) -> None:
        report = self._report(**CLUSTERED)

        json.dumps(report.describe())  # type: ignore[attr-defined]

    def test_the_report_publishes_its_conventions(self) -> None:
        described = self._report(**CLUSTERED).describe()  # type: ignore[attr-defined]

        assert described["conventions"]["monitoring"] == "session_close"
        assert described["conventions"]["window"] == "expanding"
        assert "non-overlapping" in described["conventions"]["independence"]


class TestBacktestComposition:
    """The asset layer meeting the scorer, over the synthetic asset only."""

    def test_an_asset_is_scored_through_its_own_declarations(self) -> None:
        prices = price_series(periods=400)
        result = backtest_asset(
            SYNTHETIC,
            prices=prices,
            request=WalkForwardRequest(horizons=(5,), step=5, min_observations=100),
            n_paths=300,
        )

        assert result.records
        assert result.subject["model"]["id"] == SYNTHETIC.vol_defaults.default_model
        assert result.subject["transform"]["id"] == SYNTHETIC.return_transform.id

    def test_the_null_inherits_the_venue_limit_rather_than_ignoring_it(self) -> None:
        """A null simulated without the price limit would be beaten for the wrong reason."""
        prices = price_series(periods=400)
        result = backtest_asset(
            SYNTHETIC,
            prices=prices,
            request=WalkForwardRequest(horizons=(5,), step=5, min_observations=100),
            n_paths=300,
        )

        assert SYNTHETIC.vol_defaults.session_limit is not None
        assert result.baseline["label"] == "random_walk"

    def test_the_described_block_is_json_safe(self) -> None:
        prices = price_series(periods=400)
        result = backtest_asset(
            SYNTHETIC,
            prices=prices,
            request=WalkForwardRequest(horizons=(5,), step=5, min_observations=100),
            n_paths=300,
        )

        json.dumps(describe_backtest(SYNTHETIC, result))
